---
title: "Model"
author: "JVWCD Capstone Group"
date: "3/29/2022"
output: 
  html_document:
    highlight: breezedark
    number_sections: yes
    toc: yes
    fig_width: 15
    fig_height: 10
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Data

## Packages

```{r echo=T, results='hide', message=F, warning=F}
list.of.packages <- c("tidyverse",
                      "lubridate",
                      "chron",
                      "knitr",
                      "corrplot",
                      "caret",
                      "scales",
                      "gridExtra",
                      "useful",
                      "ISOweek",
                      "kableExtra")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(tidyverse)
library(lubridate)
library(chron)
library(knitr)
library(corrplot)
library(caret)
library(scales)
library(gridExtra)
library(useful)
library(ISOweek)
library(kableExtra)
```

## Read CSV files and pre process

### Weather Data

```{r}
wa <- read.csv("new_weather_slc_airport.csv")%>%
  mutate(season = ifelse(CalendarMonth %in% c('03','04','05'), 'Spring',
                         ifelse(CalendarMonth %in% c('06','07','08'), 'Summer',
                                ifelse(CalendarMonth %in% c('09','10','11'), 'Fall',
                                       ifelse(CalendarMonth %in% c('12','01','02'), 'Winter','0')))),
         RainDays = factor(RainDays),
         date = as.Date(WeatherDate,format="%m/%d/%Y"))%>%
  filter(CalendarYear>=2020)
```

### System Demand Data

```{r}
sd <- read.csv("new_daily_demand.csv")%>%
  rename('avg_demand_cfs' = 'Avg.Daily.Demand..cfs.',
         'avg_demand_af' = 'Avg.Daily.Demand..af.',
         'avg_demand_mgd' = 'Avg.Daily.Demand..mgd.',
         'max_demand_cfs' = 'Max.Daily.Demand..cfs.',
         'max_demand_af' = 'Max.Daily.Demand..af.',
         'max_demand_mgd' = 'Max.Daily.Demand..mgd.',
         'min_demand_cfs' = 'Min.Daily.Demand..cfs.',
         'min_demand_af' = 'Min.Daily.Demand..af.',
         'min_demand_mgd' = 'Max.Daily.Demand..mgd..1')%>%#assumed this was a min
  mutate(date = as.Date(ReadDate,format="%m/%d/%Y"))
```

### Join Weather and Demand Data

```{r}
wd <- merge(wa,sd,by="date")%>%
  select(-WeatherDate)

```

# Split into Train and test

```{r}
set.seed(6496)

ti <- createDataPartition(wd$avg_demand_cfs, p=0.7,
                         list = FALSE)

train <- wd[ti,]
test <- wd[-ti,]

summary(train)
```

